/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author MINH THIEN
 */
public class DVDManagement extends javax.swing.JFrame {

    /**
     * Creates new form DVDManagement
     */
    public DVDManagement() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_title = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        panel_total = new javax.swing.JPanel();
        panel_dvdmanagement = new javax.swing.JPanel();
        lb_dvdid = new javax.swing.JLabel();
        lb_getdvdid = new javax.swing.JLabel();
        lb_dvdname = new javax.swing.JLabel();
        lb_cusaddress = new javax.swing.JLabel();
        lb_cusphone = new javax.swing.JLabel();
        tf_getdvdname = new javax.swing.JTextField();
        tf_getcusaddress = new javax.swing.JTextField();
        tf_getcusphone = new javax.swing.JTextField();
        panel_inputidcus = new javax.swing.JPanel();
        tf_dvdid = new javax.swing.JTextField();
        panel_cuslist = new javax.swing.JPanel();
        scroll_cuslist = new javax.swing.JScrollPane();
        tab_cuslist = new javax.swing.JTable();
        btn_adddvd = new javax.swing.JButton();
        btn_deletedvd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_title.setBackground(new java.awt.Color(51, 102, 255));
        panel_title.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 0, 0)));

        lb_title.setFont(new java.awt.Font("Times New Roman", 1, 43)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("DVD/DISK MANAGEMENT");

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("X");
        btn_exit.setOpaque(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_titleLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_exit)
                .addContainerGap())
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGroup(panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_titleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_titleLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(panel_title, java.awt.BorderLayout.PAGE_START);

        panel_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        panel_dvdmanagement.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "DVD/DISK Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lb_dvdid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_dvdid.setText("DVD/DISK ID:");

        lb_getdvdid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getdvdid.setText("00111");

        lb_dvdname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_dvdname.setText("DVD/DISK Name:");

        lb_cusaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_cusaddress.setText("Customer Address:");

        lb_cusphone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_cusphone.setText("Customer Phone:");

        tf_getdvdname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tf_getcusphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_dvdmanagementLayout = new javax.swing.GroupLayout(panel_dvdmanagement);
        panel_dvdmanagement.setLayout(panel_dvdmanagementLayout);
        panel_dvdmanagementLayout.setHorizontalGroup(
            panel_dvdmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dvdmanagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dvdmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_cusaddress)
                    .addComponent(lb_cusphone)
                    .addComponent(lb_dvdname)
                    .addComponent(lb_dvdid))
                .addGap(31, 31, 31)
                .addGroup(panel_dvdmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_getdvdid, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(tf_getdvdname)
                    .addComponent(tf_getcusaddress)
                    .addComponent(tf_getcusphone))
                .addContainerGap())
        );
        panel_dvdmanagementLayout.setVerticalGroup(
            panel_dvdmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dvdmanagementLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(panel_dvdmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dvdid)
                    .addComponent(lb_getdvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panel_dvdmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dvdname)
                    .addComponent(tf_getdvdname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_dvdmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cusaddress)
                    .addComponent(tf_getcusaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_dvdmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cusphone)
                    .addComponent(tf_getcusphone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        panel_inputidcus.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Input DVD/DISK ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        javax.swing.GroupLayout panel_inputidcusLayout = new javax.swing.GroupLayout(panel_inputidcus);
        panel_inputidcus.setLayout(panel_inputidcusLayout);
        panel_inputidcusLayout.setHorizontalGroup(
            panel_inputidcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inputidcusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_dvdid, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_inputidcusLayout.setVerticalGroup(
            panel_inputidcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputidcusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_dvdid, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_cuslist.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "DVD/DISK List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        tab_cuslist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_cuslist.setViewportView(tab_cuslist);

        javax.swing.GroupLayout panel_cuslistLayout = new javax.swing.GroupLayout(panel_cuslist);
        panel_cuslist.setLayout(panel_cuslistLayout);
        panel_cuslistLayout.setHorizontalGroup(
            panel_cuslistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cuslistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_cuslist)
                .addContainerGap())
        );
        panel_cuslistLayout.setVerticalGroup(
            panel_cuslistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cuslistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_cuslist, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_adddvd.setBackground(new java.awt.Color(0, 153, 255));
        btn_adddvd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_adddvd.setForeground(new java.awt.Color(255, 255, 255));
        btn_adddvd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btn_adddvd.setText("THÊM");

        btn_deletedvd.setBackground(new java.awt.Color(0, 153, 255));
        btn_deletedvd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_deletedvd.setForeground(new java.awt.Color(204, 0, 51));
        btn_deletedvd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
        btn_deletedvd.setText("XÓA");

        javax.swing.GroupLayout panel_totalLayout = new javax.swing.GroupLayout(panel_total);
        panel_total.setLayout(panel_totalLayout);
        panel_totalLayout.setHorizontalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(panel_cuslist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(panel_dvdmanagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_totalLayout.createSequentialGroup()
                                .addComponent(btn_adddvd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_deletedvd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel_inputidcus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );
        panel_totalLayout.setVerticalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(panel_inputidcus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_adddvd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_deletedvd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_dvdmanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_cuslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panel_total, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DVDManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DVDManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DVDManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DVDManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DVDManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adddvd;
    private javax.swing.JButton btn_deletedvd;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel lb_cusaddress;
    private javax.swing.JLabel lb_cusphone;
    private javax.swing.JLabel lb_dvdid;
    private javax.swing.JLabel lb_dvdname;
    private javax.swing.JLabel lb_getdvdid;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPanel panel_cuslist;
    private javax.swing.JPanel panel_dvdmanagement;
    private javax.swing.JPanel panel_inputidcus;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_total;
    private javax.swing.JScrollPane scroll_cuslist;
    private javax.swing.JTable tab_cuslist;
    private javax.swing.JTextField tf_dvdid;
    private javax.swing.JTextField tf_getcusaddress;
    private javax.swing.JTextField tf_getcusphone;
    private javax.swing.JTextField tf_getdvdname;
    // End of variables declaration//GEN-END:variables
}
