/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author MINH THIEN
 */
public class Flashcreen extends javax.swing.JFrame {

    public Flashcreen() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_load = new javax.swing.JLabel();
        progress_load = new javax.swing.JProgressBar();
        lb_percent = new javax.swing.JLabel();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_load.setBackground(new java.awt.Color(255, 255, 255));
        lb_load.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_load.setForeground(new java.awt.Color(255, 255, 255));
        lb_load.setText("Đang tải :");
        getContentPane().add(lb_load, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 355, -1, -1));

        progress_load.setBackground(new java.awt.Color(255, 255, 255));
        progress_load.setForeground(new java.awt.Color(153, 0, 0));
        progress_load.setBorderPainted(false);
        getContentPane().add(progress_load, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 310, 10));

        lb_percent.setBackground(new java.awt.Color(255, 255, 255));
        lb_percent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_percent.setForeground(new java.awt.Color(255, 255, 255));
        lb_percent.setText("99%");
        getContentPane().add(lb_percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 355, 33, 20));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flashcreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flashcreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flashcreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flashcreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flashcreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_load;
    public javax.swing.JLabel lb_percent;
    public javax.swing.JProgressBar progress_load;
    // End of variables declaration//GEN-END:variables
}
