/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Toolkit;

/**
 *
 * @author MINH THIEN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
//        Toolkit toolkit = Toolkit.getDefaultToolkit();
//        int xsize = (int) toolkit.getScreenSize().getWidth();
//        int ysize = (int) toolkit.getScreenSize().getHeight();
//        setSize(xsize, ysize);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_report = new javax.swing.JButton();
        btn_rent = new javax.swing.JButton();
        btn_return = new javax.swing.JButton();
        btn_qlcustomer = new javax.swing.JButton();
        btn_qlemployee = new javax.swing.JButton();
        btn_reservation1 = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        btn_report.setBackground(new java.awt.Color(255, 255, 255));
        btn_report.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btn_report.setText("REPORT");
        btn_report.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        getContentPane().add(btn_report);
        btn_report.setBounds(520, 530, 270, 80);

        btn_rent.setBackground(new java.awt.Color(255, 255, 255));
        btn_rent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_rent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rent.png"))); // NOI18N
        btn_rent.setText("RENT DVD/DISK");
        btn_rent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rent);
        btn_rent.setBounds(180, 180, 270, 80);

        btn_return.setBackground(new java.awt.Color(255, 255, 255));
        btn_return.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        btn_return.setText("RETURN DVD/DISK");
        btn_return.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return);
        btn_return.setBounds(180, 360, 270, 80);

        btn_qlcustomer.setBackground(new java.awt.Color(255, 255, 255));
        btn_qlcustomer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_qlcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disk.png"))); // NOI18N
        btn_qlcustomer.setText("TITLE MANAGERMENT");
        btn_qlcustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_qlcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_qlcustomer);
        btn_qlcustomer.setBounds(180, 530, 270, 80);

        btn_qlemployee.setBackground(new java.awt.Color(255, 255, 255));
        btn_qlemployee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_qlemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manager.png"))); // NOI18N
        btn_qlemployee.setText("EMPLOYEE MANAGERMENT");
        btn_qlemployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_qlemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlemployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_qlemployee);
        btn_qlemployee.setBounds(520, 180, 270, 80);

        btn_reservation1.setBackground(new java.awt.Color(255, 255, 255));
        btn_reservation1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_reservation1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reserve.png"))); // NOI18N
        btn_reservation1.setText("RESERVATION");
        btn_reservation1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_reservation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservation1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reservation1);
        btn_reservation1.setBounds(520, 360, 270, 80);

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("X");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(840, 10, 50, 30);

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_home.png"))); // NOI18N
        lb_background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lb_background);
        lb_background.setBounds(0, 0, 900, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportActionPerformed

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_returnActionPerformed

    private void btn_qlemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlemployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_qlemployeeActionPerformed

    private void btn_reservation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reservation1ActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_rentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rentActionPerformed
        Rent rent = new Rent();
        rent.setVisible(true);
    }//GEN-LAST:event_btn_rentActionPerformed

    private void btn_qlcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlcustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_qlcustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_qlcustomer;
    private javax.swing.JButton btn_qlemployee;
    private javax.swing.JButton btn_rent;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_reservation1;
    private javax.swing.JButton btn_return;
    private javax.swing.JLabel lb_background;
    // End of variables declaration//GEN-END:variables
}
