/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Toolkit;

/**
 *
 * @author MINH THIEN
 */
public class Rent extends javax.swing.JFrame {

    /**
     * Creates new form Rent
     */
    public Rent() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_title = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        panel_total = new javax.swing.JPanel();
        panel_cusid = new javax.swing.JPanel();
        tf_cusid = new javax.swing.JTextField();
        panel_cusinfo = new javax.swing.JPanel();
        lb_name = new javax.swing.JLabel();
        lb_address = new javax.swing.JLabel();
        lb_phone = new javax.swing.JLabel();
        lb_getname = new javax.swing.JLabel();
        lb_getaddress = new javax.swing.JLabel();
        lb_getphone = new javax.swing.JLabel();
        panel_iddvd = new javax.swing.JPanel();
        tf_iddvd = new javax.swing.JTextField();
        panel_dvdinfo = new javax.swing.JPanel();
        scroll_dvdinfo = new javax.swing.JScrollPane();
        table_dvdinfo = new javax.swing.JTable();
        lb_logo = new javax.swing.JLabel();
        lb_pay = new javax.swing.JLabel();
        lb_money = new javax.swing.JLabel();
        btn_pay = new javax.swing.JButton();
        lb_vnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(887, 700));

        panel_title.setBackground(new java.awt.Color(51, 102, 255));
        panel_title.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 0, 0)));

        lb_title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("RENT DVD/DISK");

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("X");
        btn_exit.setOpaque(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_titleLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btn_exit)
                .addContainerGap())
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_title, java.awt.BorderLayout.PAGE_START);

        panel_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panel_total.setPreferredSize(new java.awt.Dimension(887, 6));

        panel_cusid.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Import Customer ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        javax.swing.GroupLayout panel_cusidLayout = new javax.swing.GroupLayout(panel_cusid);
        panel_cusid.setLayout(panel_cusidLayout);
        panel_cusidLayout.setHorizontalGroup(
            panel_cusidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_cusid, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_cusidLayout.setVerticalGroup(
            panel_cusidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_cusid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panel_cusinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Customer Infomation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        lb_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_name.setText("Name:");

        lb_address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_address.setText("Address:");

        lb_phone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_phone.setText("Phone Number:");

        lb_getname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getname.setText("Võ Minh Thiện");

        lb_getaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getaddress.setText("194 Trần Bá Giao");

        lb_getphone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getphone.setText("0123012301203");

        javax.swing.GroupLayout panel_cusinfoLayout = new javax.swing.GroupLayout(panel_cusinfo);
        panel_cusinfo.setLayout(panel_cusinfoLayout);
        panel_cusinfoLayout.setHorizontalGroup(
            panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_name)
                    .addComponent(lb_address)
                    .addComponent(lb_phone))
                .addGap(6, 6, 6)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_getname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_getaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(lb_getphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_cusinfoLayout.setVerticalGroup(
            panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_name)
                    .addGroup(panel_cusinfoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lb_getname, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_address)
                    .addComponent(lb_getaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_getphone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_phone))
                .addGap(24, 24, 24))
        );

        panel_iddvd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Import DVD/DISK ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        javax.swing.GroupLayout panel_iddvdLayout = new javax.swing.GroupLayout(panel_iddvd);
        panel_iddvd.setLayout(panel_iddvdLayout);
        panel_iddvdLayout.setHorizontalGroup(
            panel_iddvdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_iddvdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_iddvd)
                .addContainerGap())
        );
        panel_iddvdLayout.setVerticalGroup(
            panel_iddvdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_iddvdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_iddvd, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_dvdinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Information DVD/DISK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        table_dvdinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_dvdinfo.setViewportView(table_dvdinfo);

        javax.swing.GroupLayout panel_dvdinfoLayout = new javax.swing.GroupLayout(panel_dvdinfo);
        panel_dvdinfo.setLayout(panel_dvdinfoLayout);
        panel_dvdinfoLayout.setHorizontalGroup(
            panel_dvdinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dvdinfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(scroll_dvdinfo)
                .addContainerGap())
        );
        panel_dvdinfoLayout.setVerticalGroup(
            panel_dvdinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dvdinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_dvdinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dvd_video.png"))); // NOI18N

        lb_pay.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lb_pay.setText("TEMPORARY CALCULATING");

        lb_money.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        lb_money.setForeground(new java.awt.Color(255, 0, 0));
        lb_money.setText("0000000000");

        btn_pay.setBackground(new java.awt.Color(255, 255, 255));
        btn_pay.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pay.png"))); // NOI18N
        btn_pay.setText("Pay");

        lb_vnd.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lb_vnd.setText("VNĐ");

        javax.swing.GroupLayout panel_totalLayout = new javax.swing.GroupLayout(panel_total);
        panel_total.setLayout(panel_totalLayout);
        panel_totalLayout.setHorizontalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_dvdinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_totalLayout.createSequentialGroup()
                                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panel_cusid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panel_iddvd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(panel_cusinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(lb_logo)
                        .addGap(26, 26, 26)
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_totalLayout.createSequentialGroup()
                                .addComponent(lb_money, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_vnd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(panel_totalLayout.createSequentialGroup()
                                .addComponent(lb_pay)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        panel_totalLayout.setVerticalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_cusinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(panel_cusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panel_iddvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_dvdinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(lb_pay)
                        .addGap(18, 18, 18)
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_money, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_vnd, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                    .addComponent(lb_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );

        getContentPane().add(panel_total, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_pay;
    private javax.swing.JLabel lb_address;
    private javax.swing.JLabel lb_getaddress;
    private javax.swing.JLabel lb_getname;
    private javax.swing.JLabel lb_getphone;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_money;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_pay;
    private javax.swing.JLabel lb_phone;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_vnd;
    private javax.swing.JPanel panel_cusid;
    private javax.swing.JPanel panel_cusinfo;
    private javax.swing.JPanel panel_dvdinfo;
    private javax.swing.JPanel panel_iddvd;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_total;
    private javax.swing.JScrollPane scroll_dvdinfo;
    private javax.swing.JTable table_dvdinfo;
    private javax.swing.JTextField tf_cusid;
    private javax.swing.JTextField tf_iddvd;
    // End of variables declaration//GEN-END:variables
}
