/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author MINH THIEN
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_title3 = new javax.swing.JPanel();
        lb_title3 = new javax.swing.JLabel();
        btn_exit3 = new javax.swing.JButton();
        panel_total = new javax.swing.JPanel();
        pane_dvdreservation = new javax.swing.JPanel();
        lb_dvdid = new javax.swing.JLabel();
        lb_getdvdid = new javax.swing.JLabel();
        lb_dvdname = new javax.swing.JLabel();
        lb_dvdaddress = new javax.swing.JLabel();
        lb_ = new javax.swing.JLabel();
        lb_getdvdname = new javax.swing.JLabel();
        lb_cusaddress1 = new javax.swing.JLabel();
        lb_1 = new javax.swing.JLabel();
        panel_cusreservation = new javax.swing.JPanel();
        tf_cusid = new javax.swing.JTextField();
        lb_cusname = new javax.swing.JLabel();
        lb_getcusname = new javax.swing.JLabel();
        lb_cusaddress = new javax.swing.JLabel();
        lb_getcusaddress = new javax.swing.JLabel();
        lb_cusphone = new javax.swing.JLabel();
        lb_getcusphone = new javax.swing.JLabel();
        panel_listreservation = new javax.swing.JPanel();
        scroll_cuslist = new javax.swing.JScrollPane();
        tab_cuslist = new javax.swing.JTable();
        btn_confirm = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_title3.setBackground(new java.awt.Color(51, 102, 255));
        panel_title3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 0, 0)));

        lb_title3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lb_title3.setForeground(new java.awt.Color(255, 255, 255));
        lb_title3.setText("RESERVATION");

        btn_exit3.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit3.setText("X");
        btn_exit3.setOpaque(false);
        btn_exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_title3Layout = new javax.swing.GroupLayout(panel_title3);
        panel_title3.setLayout(panel_title3Layout);
        panel_title3Layout.setHorizontalGroup(
            panel_title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_title3Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(lb_title3)
                .addGap(190, 190, 190)
                .addComponent(btn_exit3)
                .addContainerGap())
        );
        panel_title3Layout.setVerticalGroup(
            panel_title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_title3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_title3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_title3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(panel_title3, java.awt.BorderLayout.CENTER);

        panel_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pane_dvdreservation.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "DVD/DISK Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lb_dvdid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_dvdid.setText("DVD/DISK ID:");

        lb_getdvdid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getdvdid.setText("00111");

        lb_dvdname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_dvdname.setText("DVD/DISK Name:");

        lb_dvdaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_dvdaddress.setText("Title Address:");

        lb_.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_.setText("Customer Phone:");

        lb_getdvdname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getdvdname.setText("Thám Tử CoNan Lừng Danh");

        lb_cusaddress1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_cusaddress1.setText("Title Address:");

        lb_1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_1.setText("Customer Phone:");

        javax.swing.GroupLayout pane_dvdreservationLayout = new javax.swing.GroupLayout(pane_dvdreservation);
        pane_dvdreservation.setLayout(pane_dvdreservationLayout);
        pane_dvdreservationLayout.setHorizontalGroup(
            pane_dvdreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_dvdreservationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_dvdreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_dvdaddress)
                    .addComponent(lb_)
                    .addComponent(lb_dvdname)
                    .addComponent(lb_dvdid))
                .addGap(31, 31, 31)
                .addGroup(pane_dvdreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_getdvdid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_getdvdname, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(lb_cusaddress1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pane_dvdreservationLayout.setVerticalGroup(
            pane_dvdreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_dvdreservationLayout.createSequentialGroup()
                .addGroup(pane_dvdreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_dvdreservationLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lb_dvdid))
                    .addGroup(pane_dvdreservationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_getdvdid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(pane_dvdreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dvdname)
                    .addComponent(lb_getdvdname))
                .addGap(40, 40, 40)
                .addGroup(pane_dvdreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dvdaddress)
                    .addComponent(lb_cusaddress1))
                .addGap(40, 40, 40)
                .addGroup(pane_dvdreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_)
                    .addComponent(lb_1))
                .addGap(30, 30, 30))
        );

        panel_cusreservation.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Input Customer ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lb_cusname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_cusname.setText("Customer Name:");

        lb_getcusname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getcusname.setText("Nguyễn Văn Tài");

        lb_cusaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_cusaddress.setText("Customer Address:");

        lb_getcusaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getcusaddress.setText("Nguyễn Văn Tài");

        lb_cusphone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_cusphone.setText("Customer Phone:");

        lb_getcusphone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getcusphone.setText("09320232");

        javax.swing.GroupLayout panel_cusreservationLayout = new javax.swing.GroupLayout(panel_cusreservation);
        panel_cusreservation.setLayout(panel_cusreservationLayout);
        panel_cusreservationLayout.setHorizontalGroup(
            panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusreservationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_cusid, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addGroup(panel_cusreservationLayout.createSequentialGroup()
                        .addGroup(panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_cusaddress)
                            .addComponent(lb_cusname)
                            .addComponent(lb_cusphone))
                        .addGap(18, 18, 18)
                        .addGroup(panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_getcusphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_getcusname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_getcusaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_cusreservationLayout.setVerticalGroup(
            panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusreservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_cusid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_getcusname)
                    .addComponent(lb_cusname, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cusaddress)
                    .addComponent(lb_getcusaddress))
                .addGap(20, 20, 20)
                .addGroup(panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cusphone)
                    .addComponent(lb_getcusphone))
                .addGap(20, 20, 20))
        );

        panel_listreservation.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Reservation List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        tab_cuslist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_cuslist.setViewportView(tab_cuslist);

        javax.swing.GroupLayout panel_listreservationLayout = new javax.swing.GroupLayout(panel_listreservation);
        panel_listreservation.setLayout(panel_listreservationLayout);
        panel_listreservationLayout.setHorizontalGroup(
            panel_listreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_listreservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_cuslist)
                .addContainerGap())
        );
        panel_listreservationLayout.setVerticalGroup(
            panel_listreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_listreservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_cuslist, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_confirm.setBackground(new java.awt.Color(0, 153, 255));
        btn_confirm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_blue.png"))); // NOI18N
        btn_confirm.setText("CANCEL");

        btn_cancel.setBackground(new java.awt.Color(0, 153, 255));
        btn_cancel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btn_cancel.setText("CONFIRM");

        javax.swing.GroupLayout panel_totalLayout = new javax.swing.GroupLayout(panel_total);
        panel_total.setLayout(panel_totalLayout);
        panel_totalLayout.setHorizontalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(panel_listreservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(pane_dvdreservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_cusreservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_totalLayout.createSequentialGroup()
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        panel_totalLayout.setVerticalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(panel_cusreservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pane_dvdreservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_listreservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panel_total, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exit3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exit3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_exit1;
    private javax.swing.JButton btn_exit2;
    private javax.swing.JButton btn_exit3;
    private javax.swing.JLabel lb_;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_cusaddress;
    private javax.swing.JLabel lb_cusaddress1;
    private javax.swing.JLabel lb_cusname;
    private javax.swing.JLabel lb_cusphone;
    private javax.swing.JLabel lb_dvdaddress;
    private javax.swing.JLabel lb_dvdid;
    private javax.swing.JLabel lb_dvdname;
    private javax.swing.JLabel lb_getcusaddress;
    private javax.swing.JLabel lb_getcusname;
    private javax.swing.JLabel lb_getcusphone;
    private javax.swing.JLabel lb_getdvdid;
    private javax.swing.JLabel lb_getdvdname;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_title1;
    private javax.swing.JLabel lb_title2;
    private javax.swing.JLabel lb_title3;
    private javax.swing.JPanel pane_dvdreservation;
    private javax.swing.JPanel panel_cusreservation;
    private javax.swing.JPanel panel_listreservation;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_title1;
    private javax.swing.JPanel panel_title2;
    private javax.swing.JPanel panel_title3;
    private javax.swing.JPanel panel_total;
    private javax.swing.JScrollPane scroll_cuslist;
    private javax.swing.JTable tab_cuslist;
    private javax.swing.JTextField tf_cusid;
    // End of variables declaration//GEN-END:variables
}
