/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import entities.Customer;
import entities.Disks;
import Controll.CustomerDAO;
import entities.Title;
import Controll.DisksDAO;
import Controll.ReservationDAO;
import entities.Resevation;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author MINH THIEN
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    TitleManagement titlemanage = new TitleManagement();
    Title title = titlemanage.getTitlepub();
    CustomerDAO cusDao = new CustomerDAO();
    DisksDAO diskDao = new DisksDAO();
    ReservationDAO reserveDao = new ReservationDAO();
    public Reservation() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_total = new javax.swing.JPanel();
        panel_cusid = new javax.swing.JPanel();
        tf_cusid = new javax.swing.JTextField();
        panel_cusinfo = new javax.swing.JPanel();
        lb_getname = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        lb_address = new javax.swing.JLabel();
        lb_getaddress = new javax.swing.JLabel();
        lb_phone = new javax.swing.JLabel();
        lb_getphone = new javax.swing.JLabel();
        lb_datereservation = new javax.swing.JLabel();
        lb_getdatereservation = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_confirm = new javax.swing.JButton();
        panel_title = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_total.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        panel_cusid.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Input Customer ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        tf_cusid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_cusidKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel_cusidLayout = new javax.swing.GroupLayout(panel_cusid);
        panel_cusid.setLayout(panel_cusidLayout);
        panel_cusidLayout.setHorizontalGroup(
            panel_cusidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_cusid, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cusidLayout.setVerticalGroup(
            panel_cusidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_cusid, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_cusinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lb_getname.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        lb_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_name.setText("Name:");

        lb_address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_address.setText("Address:");

        lb_getaddress.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        lb_phone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_phone.setText("Phone Number:");

        lb_getphone.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        lb_datereservation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_datereservation.setText("Date Of Reservation:");

        lb_getdatereservation.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        javax.swing.GroupLayout panel_cusinfoLayout = new javax.swing.GroupLayout(panel_cusinfo);
        panel_cusinfo.setLayout(panel_cusinfoLayout);
        panel_cusinfoLayout.setHorizontalGroup(
            panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_name)
                    .addComponent(lb_address)
                    .addComponent(lb_phone))
                .addGap(31, 31, 31)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cusinfoLayout.createSequentialGroup()
                        .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_getphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_getname, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_datereservation)
                        .addGap(31, 31, 31)
                        .addComponent(lb_getdatereservation, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addComponent(lb_getaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_cusinfoLayout.setVerticalGroup(
            panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusinfoLayout.createSequentialGroup()
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cusinfoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_getname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_name)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cusinfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_getdatereservation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_datereservation))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_address)
                    .addComponent(lb_getaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_getphone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_phone))
                .addGap(24, 24, 24))
        );

        btn_cancel.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 0, 0));
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel40.png"))); // NOI18N
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_confirm.setBackground(new java.awt.Color(255, 255, 255));
        btn_confirm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirm40.png"))); // NOI18N
        btn_confirm.setText("CONFIRM");
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_totalLayout = new javax.swing.GroupLayout(panel_total);
        panel_total.setLayout(panel_totalLayout);
        panel_totalLayout.setHorizontalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_totalLayout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85)
                            .addComponent(btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(panel_cusinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_cusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_totalLayout.setVerticalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_cusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panel_cusinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_confirm))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panel_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 340));

        panel_title.setBackground(new java.awt.Color(51, 102, 255));
        panel_title.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 0, 0)));

        lb_title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("Make Reservation");

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("X");
        btn_exit.setOpaque(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(lb_title)
                .addGap(95, 95, 95)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGroup(panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_titleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162))
        );

        getContentPane().add(panel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        setVisible(false);
        titlemanage.setVisible(true);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        setVisible(false);
        titlemanage.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void tf_cusidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cusidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String id = tf_cusid.getText().toString();
            try {
                Customer cus = cusDao.findByID(id);
                lb_getname.setText(cus.getCustomerName());
                lb_getaddress.setText(cus.getAddress());
                lb_getphone.setText(cus.getPhoneNumber());
                lb_getdatereservation.setText(LocalDate.now().toString());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tf_cusidKeyPressed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed

        List<Disks> listDisk = diskDao.findDiskByIdTitle(title.getTitleID());
        Customer customer = cusDao.findByID(tf_cusid.getText().toString());
        boolean flag = false;
        for(int i =0;i<listDisk.size();i++){
            if(listDisk.get(i).getStatus().equalsIgnoreCase("On Shelves")){
                JOptionPane.showMessageDialog(this, "The Disk is still on the shelf");
                flag = false;
                break;
            }else{
                flag = true;
            }
        }
        if(flag = true){
            Resevation reserve = new Resevation();
            reserve.setReverationID(makeNewID());
            reserve.setTitle(title);
            reserve.setCustomer(customer);
            reserve.setDayReserve(LocalDate.now());
            reserveDao.save(reserve);
            JOptionPane.showMessageDialog(this, "Make reservation is successfully");
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }
    public String makeNewID() {
        int temp = 0;
        List<Resevation> listReserve = reserveDao.getAll(Resevation.class);
        for (int i = 0; i < listReserve.size(); i++) {
            if (Integer.parseInt(listReserve.get(i).getReverationID()) > temp) {
                temp = Integer.parseInt(listReserve.get(i).getReverationID());
            }
        }
        temp++;
        String newID = "" + temp;
        return newID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel lb_address;
    private javax.swing.JLabel lb_datereservation;
    private javax.swing.JLabel lb_getaddress;
    private javax.swing.JLabel lb_getdatereservation;
    private javax.swing.JLabel lb_getname;
    private javax.swing.JLabel lb_getphone;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_phone;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPanel panel_cusid;
    private javax.swing.JPanel panel_cusinfo;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_total;
    private javax.swing.JTextField tf_cusid;
    // End of variables declaration//GEN-END:variables
}
