/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author MINH THIEN
 */
public class Return extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_title = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        panel_total = new javax.swing.JPanel();
        panel_cusinfo = new javax.swing.JPanel();
        lb_name = new javax.swing.JLabel();
        lb_address = new javax.swing.JLabel();
        lb_phone = new javax.swing.JLabel();
        lb_getname = new javax.swing.JLabel();
        lb_getaddress = new javax.swing.JLabel();
        lb_getphone = new javax.swing.JLabel();
        lb_dayofhire = new javax.swing.JLabel();
        lb_getdayofhire = new javax.swing.JLabel();
        lb_dayofreturn = new javax.swing.JLabel();
        lb_getdayofreturn = new javax.swing.JLabel();
        panel_iddvd = new javax.swing.JPanel();
        tf_iddvd = new javax.swing.JTextField();
        panel_dvdinforeturn = new javax.swing.JPanel();
        scroll_dvdinforeturn = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_confirm = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(887, 700));

        panel_title.setBackground(new java.awt.Color(51, 102, 255));
        panel_title.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 0, 0)));

        lb_title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("RETURN DVD/DISK");

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("X");
        btn_exit.setOpaque(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_titleLayout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(lb_title)
                .addGap(110, 110, 110)
                .addComponent(btn_exit)
                .addContainerGap())
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_title, java.awt.BorderLayout.PAGE_START);

        panel_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        panel_cusinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Customer Infomation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        lb_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_name.setText("Name:");

        lb_address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_address.setText("Address:");

        lb_phone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_phone.setText("Phone Number:");

        lb_getname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getname.setText("Võ Minh Thiện");

        lb_getaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getaddress.setText("194 Trần Bá Giao");

        lb_getphone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getphone.setText("0123012301203");

        lb_dayofhire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_dayofhire.setText("Day of hire:");

        lb_getdayofhire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getdayofhire.setText("1/12/2019");

        lb_dayofreturn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_dayofreturn.setText("Day of return:");

        lb_getdayofreturn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_getdayofreturn.setText("1/2/2019");

        javax.swing.GroupLayout panel_cusinfoLayout = new javax.swing.GroupLayout(panel_cusinfo);
        panel_cusinfo.setLayout(panel_cusinfoLayout);
        panel_cusinfoLayout.setHorizontalGroup(
            panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_name)
                    .addComponent(lb_address)
                    .addComponent(lb_phone))
                .addGap(6, 6, 6)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_getphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cusinfoLayout.createSequentialGroup()
                        .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_getname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_getaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_dayofhire)
                            .addComponent(lb_dayofreturn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_cusinfoLayout.createSequentialGroup()
                                .addComponent(lb_getdayofreturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(77, 77, 77))
                            .addComponent(lb_getdayofhire, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        panel_cusinfoLayout.setVerticalGroup(
            panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_name)
                    .addGroup(panel_cusinfoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_dayofhire)
                                .addComponent(lb_getdayofhire, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                            .addComponent(lb_getname, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_address)
                    .addComponent(lb_getaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_getdayofreturn)
                    .addComponent(lb_dayofreturn))
                .addGap(31, 31, 31)
                .addGroup(panel_cusinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_getphone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_phone))
                .addGap(24, 24, 24))
        );

        panel_iddvd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Import DVD/DISK ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        javax.swing.GroupLayout panel_iddvdLayout = new javax.swing.GroupLayout(panel_iddvd);
        panel_iddvd.setLayout(panel_iddvdLayout);
        panel_iddvdLayout.setHorizontalGroup(
            panel_iddvdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_iddvdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_iddvd, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_iddvdLayout.setVerticalGroup(
            panel_iddvdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_iddvdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_iddvd, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_dvdinforeturn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Information DVD/DISK Return", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_dvdinforeturn.setViewportView(jTable1);

        javax.swing.GroupLayout panel_dvdinforeturnLayout = new javax.swing.GroupLayout(panel_dvdinforeturn);
        panel_dvdinforeturn.setLayout(panel_dvdinforeturnLayout);
        panel_dvdinforeturnLayout.setHorizontalGroup(
            panel_dvdinforeturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dvdinforeturnLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(scroll_dvdinforeturn)
                .addContainerGap())
        );
        panel_dvdinforeturnLayout.setVerticalGroup(
            panel_dvdinforeturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dvdinforeturnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_dvdinforeturn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_confirm.setBackground(new java.awt.Color(255, 255, 255));
        btn_confirm.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_confirm.setIcon(new javax.swing.ImageIcon("D:\\Code_NetBean\\QuanLyBangDia\\src\\images\\confirm.png")); // NOI18N
        btn_confirm.setText("Confirm");

        btn_cancel.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(204, 0, 0));
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btn_cancel.setText("Cancel");

        javax.swing.GroupLayout panel_totalLayout = new javax.swing.GroupLayout(panel_total);
        panel_total.setLayout(panel_totalLayout);
        panel_totalLayout.setHorizontalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_dvdinforeturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_totalLayout.createSequentialGroup()
                                .addComponent(panel_iddvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel_cusinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cancel)
                        .addGap(18, 18, 18)
                        .addComponent(btn_confirm)
                        .addGap(23, 23, 23))))
        );
        panel_totalLayout.setVerticalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_cusinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_iddvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_dvdinforeturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(panel_total, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_exit;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_address;
    private javax.swing.JLabel lb_dayofhire;
    private javax.swing.JLabel lb_dayofreturn;
    private javax.swing.JLabel lb_getaddress;
    private javax.swing.JLabel lb_getdayofhire;
    private javax.swing.JLabel lb_getdayofreturn;
    private javax.swing.JLabel lb_getname;
    private javax.swing.JLabel lb_getphone;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_phone;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPanel panel_cusinfo;
    private javax.swing.JPanel panel_dvdinforeturn;
    private javax.swing.JPanel panel_iddvd;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_total;
    private javax.swing.JScrollPane scroll_dvdinforeturn;
    private javax.swing.JTextField tf_iddvd;
    // End of variables declaration//GEN-END:variables
}
