/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controll.TitleDAO;
import Controll.ReservationDAO;
import entities.Resevation;
import entities.Title;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINH THIEN
 */
public class TitleManagement extends javax.swing.JFrame {

    /**
     * Creates new form TitleManagement
     */
    TitleDAO titleDao = new TitleDAO();
    ReservationDAO reserveDao = new ReservationDAO();
    public static Title titlepub;

    public static Title getTitlepub() {
        return titlepub;
    }

    public static void setTitlepub(Title titlepub) {
        TitleManagement.titlepub = titlepub;
    }

    
    
    public TitleManagement() {
        initComponents();
        setLocationRelativeTo(null);
        loadTable();
        loadReservation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_title = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        panel_total = new javax.swing.JPanel();
        panel_cusmanagement = new javax.swing.JPanel();
        lb_titleid = new javax.swing.JLabel();
        lb_gettitleid = new javax.swing.JLabel();
        lb_titlename = new javax.swing.JLabel();
        tf_gettitlename = new javax.swing.JTextField();
        btn_addtitle = new javax.swing.JButton();
        btn_updatetitle = new javax.swing.JButton();
        btn_deletetitle = new javax.swing.JButton();
        panel_inputidtitle = new javax.swing.JPanel();
        tf_inputidtitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panel_titlelist = new javax.swing.JPanel();
        scroll_titlelist = new javax.swing.JScrollPane();
        tab_titlelist = new javax.swing.JTable();
        panel_cusreservation = new javax.swing.JPanel();
        scroll_cuslist = new javax.swing.JScrollPane();
        tab_cuslist = new javax.swing.JTable();
        btn_resevation = new javax.swing.JButton();
        btn_cancelreservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_title.setBackground(new java.awt.Color(51, 102, 255));
        panel_title.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        panel_title.setPreferredSize(new java.awt.Dimension(1080, 50));

        lb_title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("TITLE MANAGEMENT");

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("X");
        btn_exit.setOpaque(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(lb_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addContainerGap())
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_titleLayout.createSequentialGroup()
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(panel_titleLayout.createSequentialGroup()
                        .addComponent(lb_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        getContentPane().add(panel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 90));

        panel_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        panel_cusmanagement.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Title Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lb_titleid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_titleid.setText("Title ID:");

        lb_gettitleid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_gettitleid.setText("00111");

        lb_titlename.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_titlename.setText("Title Name:");

        tf_gettitlename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_addtitle.setBackground(new java.awt.Color(0, 153, 255));
        btn_addtitle.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_addtitle.setForeground(new java.awt.Color(255, 255, 255));
        btn_addtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btn_addtitle.setText("ADD");
        btn_addtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addtitleActionPerformed(evt);
            }
        });

        btn_updatetitle.setBackground(new java.awt.Color(0, 153, 255));
        btn_updatetitle.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_updatetitle.setForeground(new java.awt.Color(255, 255, 255));
        btn_updatetitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_updatetitle.setText("UPDATE");
        btn_updatetitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatetitleActionPerformed(evt);
            }
        });

        btn_deletetitle.setBackground(new java.awt.Color(0, 153, 255));
        btn_deletetitle.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_deletetitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
        btn_deletetitle.setText("DELETE");
        btn_deletetitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletetitleActionPerformed(evt);
            }
        });

        panel_inputidtitle.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Input Title ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        tf_inputidtitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_inputidtitleKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel_inputidtitleLayout = new javax.swing.GroupLayout(panel_inputidtitle);
        panel_inputidtitle.setLayout(panel_inputidtitleLayout);
        panel_inputidtitleLayout.setHorizontalGroup(
            panel_inputidtitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inputidtitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_inputidtitle)
                .addContainerGap())
        );
        panel_inputidtitleLayout.setVerticalGroup(
            panel_inputidtitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputidtitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_inputidtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reload.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_cusmanagementLayout = new javax.swing.GroupLayout(panel_cusmanagement);
        panel_cusmanagement.setLayout(panel_cusmanagementLayout);
        panel_cusmanagementLayout.setHorizontalGroup(
            panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusmanagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_inputidtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_cusmanagementLayout.createSequentialGroup()
                        .addGroup(panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_titlename)
                            .addComponent(lb_titleid))
                        .addGap(67, 67, 67)
                        .addGroup(panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_gettitlename, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_cusmanagementLayout.createSequentialGroup()
                                .addComponent(lb_gettitleid, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cusmanagementLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_addtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_updatetitle)
                        .addGap(18, 18, 18)
                        .addComponent(btn_deletetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_cusmanagementLayout.setVerticalGroup(
            panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cusmanagementLayout.createSequentialGroup()
                .addGroup(panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_titleid)
                        .addComponent(lb_gettitleid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_titlename)
                    .addComponent(tf_gettitlename, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_cusmanagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updatetitle)
                    .addComponent(btn_deletetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel_inputidtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panel_titlelist.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Title List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        tab_titlelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_titlelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_titlelistMouseClicked(evt);
            }
        });
        scroll_titlelist.setViewportView(tab_titlelist);

        javax.swing.GroupLayout panel_titlelistLayout = new javax.swing.GroupLayout(panel_titlelist);
        panel_titlelist.setLayout(panel_titlelistLayout);
        panel_titlelistLayout.setHorizontalGroup(
            panel_titlelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titlelistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_titlelist, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_titlelistLayout.setVerticalGroup(
            panel_titlelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titlelistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_titlelist, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_cusreservation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Customer Reservation List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        tab_cuslist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_cuslist.setViewportView(tab_cuslist);

        javax.swing.GroupLayout panel_cusreservationLayout = new javax.swing.GroupLayout(panel_cusreservation);
        panel_cusreservation.setLayout(panel_cusreservationLayout);
        panel_cusreservationLayout.setHorizontalGroup(
            panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cusreservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_cuslist)
                .addContainerGap())
        );
        panel_cusreservationLayout.setVerticalGroup(
            panel_cusreservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cusreservationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scroll_cuslist, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        btn_resevation.setBackground(new java.awt.Color(0, 153, 255));
        btn_resevation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_resevation.setForeground(new java.awt.Color(255, 255, 255));
        btn_resevation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reserve40.png"))); // NOI18N
        btn_resevation.setText("RESERVATION");
        btn_resevation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resevationActionPerformed(evt);
            }
        });

        btn_cancelreservation.setBackground(new java.awt.Color(0, 153, 255));
        btn_cancelreservation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cancelreservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel32.png"))); // NOI18N
        btn_cancelreservation.setText(" CANCEL RESERVATION");
        btn_cancelreservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelreservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_totalLayout = new javax.swing.GroupLayout(panel_total);
        panel_total.setLayout(panel_totalLayout);
        panel_totalLayout.setHorizontalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addComponent(panel_cusmanagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(panel_titlelist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_totalLayout.createSequentialGroup()
                        .addComponent(panel_cusreservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cancelreservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_resevation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel_totalLayout.setVerticalGroup(
            panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_totalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_cusmanagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_titlelist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(panel_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_cusreservation, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_totalLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btn_resevation, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelreservation, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(panel_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 1060, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_addtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addtitleActionPerformed
        if (isEmpty()) {
            Title title = new Title();
            title.setTitleID(lb_gettitleid.getText().toString());
            title.setTitleName(tf_gettitlename.getText().toString());
            if (titleDao.save(title)) {
                JOptionPane.showMessageDialog(this, "Insert new title is successfully");
                loadTable();
            } else {
                JOptionPane.showMessageDialog(this, "Insert new title is successfully");
            }
        }
    }//GEN-LAST:event_btn_addtitleActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        clear();
        String titleid = makeNewID();
        lb_gettitleid.setText(titleid);
        loadTable();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_updatetitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatetitleActionPerformed
        try {
            if (tab_titlelist.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "You need choose the title !");
            } else {
                String id = lb_gettitleid.getText().toString();
                Title title = titleDao.findTitleByID(id);
                title.setTitleName(tf_gettitlename.getText());
                titleDao.update(title);
                JOptionPane.showMessageDialog(null, "Update title is successfully");
                loadTable();
                clear();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update title infomation failed");
        }
    }//GEN-LAST:event_btn_updatetitleActionPerformed

    private void tab_titlelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_titlelistMouseClicked
        try {
            int index = this.tab_titlelist.getSelectedRow();
            String ma = this.tab_titlelist.getValueAt(index, 0).toString();
            Title title = titleDao.findTitleByID(ma);
            this.setTitlepub(title);
            lb_gettitleid.setText(this.getTitlepub().getTitleID());
            tf_gettitlename.setText(this.getTitlepub().getTitleName());

            DefaultTableModel model = new DefaultTableModel() {
                public boolean isCellEditable(int rowIndex, int mColIndex) {
                    return false;
                }
            };
            model.addColumn("Customer ID");
            model.addColumn("Customer Name");
            model.addColumn("Customer Phone");
            model.addColumn("Day of Reservation");
            for (Resevation reservation : reserveDao.findReservationByIDTitle(ma)) {
                model.addRow(new Object[]{
                    reservation.getCustomer().getCustomerID(),
                    reservation.getCustomer().getCustomerName(),
                    reservation.getCustomer().getPhoneNumber(),
                    reservation.getDayReserve()
                });
                this.tab_cuslist.setModel(model);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tab_titlelistMouseClicked

    private void btn_deletetitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletetitleActionPerformed
        try {
            if (tab_titlelist.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "You need select a title");
            } else {
                int dialog = JOptionPane.showConfirmDialog(this, "Do you want to delete ??", "Yes", JOptionPane.YES_NO_OPTION);
                if (dialog == JOptionPane.YES_OPTION) {
                    int index = this.tab_titlelist.getSelectedRow();
                    String id = tab_titlelist.getValueAt(index, 0).toString();
                    Title title = titleDao.findTitleByID(id);
                    titleDao.delete(title);
                    loadTable();
                    clear();
                    JOptionPane.showMessageDialog(null, "Delete is successfully !");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Delete title is failed!");
        }
    }//GEN-LAST:event_btn_deletetitleActionPerformed

    private void tf_inputidtitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_inputidtitleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String id = tf_inputidtitle.getText().toString();
            try {
                DefaultTableModel model = new DefaultTableModel() {
                    public boolean isCellEditable(int rowIndex, int mColIndex) {
                        return false;
                    }
                };
                model.addColumn("Title ID");
                model.addColumn("Title Name");
                Title title = titleDao.findTitleByID(id);
                model.addRow(new Object[]{
                    title.getTitleID(),
                    title.getTitleName()
                });
                clear();
                this.tab_titlelist.setModel(model);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_tf_inputidtitleKeyPressed

    private void btn_resevationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resevationActionPerformed
        if (tab_titlelist.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "You need select a tilte");
            } else {
            Reservation reserve = new Reservation();
            reserve.setVisible(true);
        }
    }//GEN-LAST:event_btn_resevationActionPerformed

    private void btn_cancelreservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelreservationActionPerformed
        try {
            if (tab_cuslist.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "You need select a customer");
            } else {
                int dialog = JOptionPane.showConfirmDialog(this, "Do you want to cancel this reservation ??", "Yes", JOptionPane.YES_NO_OPTION);
                if (dialog == JOptionPane.YES_NO_OPTION) {
                    int index = this.tab_cuslist.getSelectedRow();
                    String id = tab_cuslist.getValueAt(index, 0).toString();
                    Resevation reserve = reserveDao.findReservationByIDCustomer(id);
                    reserveDao.delete(reserve);
                    loadReservation();
                    clear();
                    JOptionPane.showMessageDialog(null, "Cancel is successfully !");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cancel title is failed!");
        }
    }//GEN-LAST:event_btn_cancelreservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleManagement().setVisible(true);
            }
        });
    }

    public String makeNewID() {
        int temp = 0;
        List<Title> listTitle = titleDao.getAll(Title.class);
        for (int i = 0; i < listTitle.size(); i++) {
            if (Integer.parseInt(listTitle.get(i).getTitleID()) > temp) {
                temp = Integer.parseInt(listTitle.get(i).getTitleID());
            }
        }
        temp++;
        String newID = "" + temp;
        return newID;
    }

    public void clear() {
        lb_gettitleid.setText("");
        tf_gettitlename.setText("");
        tf_inputidtitle.setText("");
    }

    public boolean isEmpty() {
        if (tf_gettitlename.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Please make sure the fields are not empty ");
            return false;
        } else {
            return true;
        }
    }

    public void loadTable() {
        DefaultTableModel model = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        model.addColumn("Title ID");
        model.addColumn("Title Name");
        for (Title title : titleDao.getAll(Title.class)) {
            model.addRow(new Object[]{
                title.getTitleID(),
                title.getTitleName()
            });
            this.tab_titlelist.setModel(model);
        }
    }
    public void loadReservation(){
         DefaultTableModel model = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        model.addColumn("Customer ID");
            model.addColumn("Customer Name");
            model.addColumn("Customer Phone");
            model.addColumn("Day of Reservation");
            for (Resevation reservation : reserveDao.getAll(Resevation.class)) {
                model.addRow(new Object[]{
                    reservation.getCustomer().getCustomerID(),
                    reservation.getCustomer().getCustomerName(),
                    reservation.getCustomer().getPhoneNumber(),
                    reservation.getDayReserve()
                });
                this.tab_cuslist.setModel(model);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addtitle;
    private javax.swing.JButton btn_cancelreservation;
    private javax.swing.JButton btn_deletetitle;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_resevation;
    private javax.swing.JButton btn_updatetitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_gettitleid;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_titleid;
    private javax.swing.JLabel lb_titlename;
    private javax.swing.JPanel panel_cusmanagement;
    private javax.swing.JPanel panel_cusreservation;
    private javax.swing.JPanel panel_inputidtitle;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_titlelist;
    private javax.swing.JPanel panel_total;
    private javax.swing.JScrollPane scroll_cuslist;
    private javax.swing.JScrollPane scroll_titlelist;
    private javax.swing.JTable tab_cuslist;
    private javax.swing.JTable tab_titlelist;
    private javax.swing.JTextField tf_gettitlename;
    private javax.swing.JTextField tf_inputidtitle;
    // End of variables declaration//GEN-END:variables
}
